spring.config.import=optional:secret.properties

spring.application.name=WiperService

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true

spring.main.banner-mode=off
spring.output.ansi.enabled=detect

logging.level.root=INFO
logging.level.kamaz.project.sandbox=DEBUG
logging.charset.console=UTF-8
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

spring.datasource.url=jdbc:postgresql://localhost:5432/sandbox
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

upload.path=./uploads/